project:
  type: website
  output-dir: docs

website:
  title: "Linnea Lauffer"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - explore.qmd

format:
  html:
    theme:
      - flatly
      - styles.scss
    mainfont: Lora
    toc: true
    page-layout: full

editor: visual

